version: '3.9'
services:
  ##########################################################################
  # 90d-backend service
  ##########################################################################
  90d-backend:
    container_name: 90d-backend
    image: darvin/90d-backend:1.0
    environment:
      - JAVA_OPTS= -Xms256M -Xmx256M
      - DATABASE_IP=192.168.100.83
      - DATABASE_PORT=1433
      - DATABASE_NAME=proyecto90d
      - DATABASE_USERNAME=darvi
      - DATABASE_PASSWORD=proyecto90d
    ports:
      - 8080:8080
    networks:
      - 90d-network

  ##########################################################################
  # 90d-backend service
  ##########################################################################
  90d-frontend:
    container_name: 90d-frontend
    image: darvin/90d-frontend:1.0
    environment:
      - REACT_APP_ENV=PRODUCTION
      - REACT_APP_AXIOS_SERVER=http://localhost:8080
      - REACT_APP_API_URL=http://localhost:8080/api/v1
      - REACT_APP_URL=http://localhost:3000
    ports:
      - 3000:80
    networks:
      - 90d-network
networks:
  90d-network: