version: '3.9'
services:
  ##########################################################################
  # 90d-backend service
  ##########################################################################
  90d-backend:
    container_name: 90d-backend
    image: sfcm250110/docker-proyecto-90d-backend:1.0
    environment:
      - JAVA_OPTS= -Xms256M -Xmx256M
      - DATABASE_IP=192.168.100.83
      - DATABASE_PORT=1433
      - DATABASE_NAME=proyecto90d
      - DATABASE_USERNAME=darvi
      - DATABASE_PASSWORD=proyecto90d
    ports:
      - 3000:80